[{
    "login": "martijn-teigeler",
    "id": 856711,
    "avatar_url": "https://secure.gravatar.com/avatar/8a9bb479fa73e8aef62f20e631d6024e?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
    "gravatar_id": "8a9bb479fa73e8aef62f20e631d6024e",
    "url": "https://api.github.com/users/martijn-teigeler",
    "html_url": "https://github.com/martijn-teigeler",
    "followers_url": "https://api.github.com/users/martijn-teigeler/followers",
    "following_url": "https://api.github.com/users/martijn-teigeler/following",
    "gists_url": "https://api.github.com/users/martijn-teigeler/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/martijn-teigeler/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/martijn-teigeler/subscriptions",
    "organizations_url": "https://api.github.com/users/martijn-teigeler/orgs",
    "repos_url": "https://api.github.com/users/martijn-teigeler/repos",
    "events_url": "https://api.github.com/users/martijn-teigeler/events{/privacy}",
    "received_events_url": "https://api.github.com/users/martijn-teigeler/received_events",
    "type": "User",
    "name": "Martijn",
    "company": "Stormcloud IDE",
    "blog": "http://stormcloud-ide.github.com/project",
    "location": "Willemstad, Curacao",
    "email": "martijn.teigeler@gmail.com",
    "hireable": false,
    "bio": null,
    "public_repos": 8,
    "followers": 3,
    "following": 7,
    "created_at": "2011-06-17T14:55:11Z",
    "updated_at": "2013-03-04T15:20:25Z",
    "public_gists": 0,
    "total_private_repos": 0,
    "owned_private_repos": 0,
    "disk_usage": 160,
    "collaborators": 0,
    "plan": {
        "name": "free",
        "space": 307200,
        "collaborators": 0,
        "private_repos": 0
    },
    "private_gists": 0
}]
